-- Seed data for pregnancy timeline
-- This file populates the pregnancy_weeks table with data for all 40 weeks of pregnancy

-- Clear existing data if any
DELETE FROM public.pregnancy_weeks;

-- Seed weeks 1-13 (First Trimester)
INSERT INTO public.pregnancy_weeks (week, fetal_development, maternal_changes, tips, nutrition_advice, common_symptoms, medical_checkups, image_url) VALUES
(1, 'Fertilization occurs. The fertilized egg (zygote) begins to divide and becomes a blastocyst.', 'Your body is preparing for pregnancy but you may not feel any different yet.', 'Start taking a prenatal vitamin with folic acid if you haven''t already.', 'Focus on foods rich in folic acid like leafy greens, citrus fruits, and beans.', 'You likely won''t experience symptoms yet.', 'Schedule a preconception visit if you haven''t already.', 'week01_poppy_seed.png'),

(2, 'The blastocyst implants in the uterine wall. The placenta and embryo begin to develop.', 'Your period is due around now, but won''t arrive. Hormone levels are changing.', 'Consider downloading a pregnancy app to track your journey.', 'Continue with a balanced diet rich in fruits, vegetables, and whole grains.', 'You may have spotting (implantation bleeding) and mild cramping.', 'Take a pregnancy test if you suspect you''re pregnant.', 'week02_poppy_seed.png'),

(3, 'The embryo is now the size of a poppy seed. The neural tube (future brain and spinal cord) begins to form.', 'Pregnancy hormones (hCG) are rising rapidly, which may trigger early symptoms.', 'Start avoiding alcohol, smoking, and limit caffeine intake.', 'Eat small, frequent meals to help with nausea. Stay hydrated.', 'You may experience nausea, fatigue, breast tenderness, and frequent urination.', 'Schedule your first prenatal appointment.', 'week03_poppy_seed.png'),

(4, 'The embryo is now about the size of a poppyseed (0.14 inches). The heart, brain, and spinal cord are beginning to develop.', 'Your body is producing more blood. You may feel more tired than usual.', 'Get plenty of rest and stay hydrated.', 'Incorporate protein-rich foods like lean meats, beans, and dairy.', 'Morning sickness, fatigue, food aversions, and heightened sense of smell.', 'First prenatal visit typically scheduled between weeks 8-12.', 'week04_poppy_seed.png'),

(5, 'The embryo is now about the size of a sesame seed (0.2 inches). The heart begins to beat and pumps blood.', 'Your blood volume continues to increase. The uterus is growing but not showing yet.', 'Begin thinking about your birth preferences and care providers.', 'Focus on iron-rich foods to support increased blood production.', 'Continued morning sickness, fatigue, and breast changes.', 'Consider genetic carrier screening if not done preconception.', 'week05_sesame_seed.png'),

(6, 'The embryo is now about the size of a lentil (0.25 inches). Facial features and limb buds are forming.', 'Your uterus is growing but not showing externally yet.', 'Start doing pregnancy-safe exercises if you feel up to it.', 'If experiencing nausea, try ginger tea or small frequent meals.', 'Morning sickness may peak, emotional changes, and food cravings or aversions.', 'Continue taking prenatal vitamins regularly.', 'week06_lentil.png'),

(7, 'The embryo is now about the size of a blueberry (0.5 inches). All essential organs are forming.', 'Hormone levels continue to rise, intensifying early pregnancy symptoms.', 'Consider joining a pregnancy support group online or in-person.', 'Focus on getting enough calcium for developing bones.', 'Strong food aversions, heightened sense of smell, and fatigue.', 'Prepare questions for your upcoming first prenatal visit.', 'week07_blueberry.png'),

(8, 'The embryo is now about the size of a raspberry (0.6 inches) and is officially called a fetus. Fingers and toes are forming.', 'Your uterus is now about the size of a tennis ball.', 'Research childbirth education classes in your area.', 'If struggling with morning sickness, ask your provider about safe remedies.', 'Persistent nausea, breast tenderness, and possibly visible veins on breasts.', 'First prenatal visit may occur this week; includes medical history review.', 'week08_raspberry.png'),

(9, 'The fetus is now about the size of a cherry (1 inch). All essential organs have formed and are beginning to function.', 'You may notice your waistband feeling tighter, but you''re not showing yet.', 'Start sleeping on your side, preferably the left side.', 'Try eating a protein snack before bed to stabilize blood sugar.', 'Fatigue may be strong, continued nausea, and mild mood swings.', 'First ultrasound may be performed to confirm pregnancy and dating.', 'week09_cherry.png'),

(10, 'The fetus is now about the size of a strawberry (1.2 inches). The tail is gone, and limbs can bend.', 'Your blood volume has increased by about 20-30%.', 'Consider telling close family and friends about your pregnancy.', 'Include plenty of fiber to help with potential constipation.', 'Reduced nausea for some, visible veins, and possible constipation.', 'Blood tests and possibly non-invasive prenatal testing (NIPT).', 'week10_strawberry.png'),

(11, 'The fetus is now about the size of a lime (1.6 inches). Tooth buds and hair follicles are forming.', 'Your uterus is now about the size of a grapefruit.', 'Make sure you''re getting enough sleep and rest.', 'Focus on vitamin C rich foods for immune support.', 'Some relief from morning sickness, slight round ligament pain.', 'Review genetic testing options with your healthcare provider.', 'week11_lime.png'),

(12, 'The fetus is now about the size of a plum (2.1 inches). Reflexes are developing, and the fetus can make a fist.', 'End of the first trimester approaches. Your uterus may be felt just above the pubic bone.', 'Start researching childcare options if you plan to return to work.', 'Reintroduce foods you may have avoided due to aversions.', 'Energy levels may improve, skin changes may begin.', 'NT (nuchal translucency) ultrasound may be performed.', 'week12_plum.png'),

(13, 'The fetus is now about the size of a peach (2.9 inches). Fingerprints are forming and the fetus can suck its thumb.', 'You may have gained 2-4 pounds. The uterus is now above the pelvic bone.', 'If you haven''t already, start thinking about a maternity wardrobe.', 'Focus on healthy fats like avocados and nuts for baby''s developing brain.', 'First trimester symptoms typically ease, but round ligament pain may increase.', 'Review first trimester screening results with your provider.', 'week13_peach.png');

-- Seed weeks 14-26 (Second Trimester)
INSERT INTO public.pregnancy_weeks (week, fetal_development, maternal_changes, tips, nutrition_advice, common_symptoms, medical_checkups, image_url) VALUES
(14, 'The fetus is now about the size of a lemon (3.4 inches). The thyroid is functioning and the face is starting to look more human.', 'You might start showing now, especially if this is not your first pregnancy.', 'Start doing Kegel exercises to strengthen your pelvic floor.', 'Ensure adequate protein intake for the baby''s rapid growth.', 'Decreased nausea, increased energy, possible skin changes.', 'Monthly prenatal visits continue.', 'week14_lemon.png'),

(15, 'The fetus is now about the size of an apple (4 inches). Bones are getting harder and the fetus can sense light.', 'Your bump may be more noticeable and you may feel more energetic.', 'Consider prenatal yoga or swimming for gentle exercise.', 'Include foods rich in calcium and vitamin D for bone development.', 'Reduced morning sickness, nasal congestion, and possible headaches.', 'Discuss second trimester screening tests with your provider.', 'week15_apple.png'),

(16, 'The fetus is now about the size of an avocado (4.6 inches). The eyes can make small movements and the ears are in position.', 'You might feel the baby move for the first time (quickening), especially if this is not your first pregnancy.', 'Begin sleeping with a pregnancy pillow for better comfort.', 'Focus on iron-rich foods to prevent anemia.', 'First baby movements for some, backaches, and round ligament pain.', 'Quad screen or AFP test may be offered around this time.', 'week16_avocado.png'),

(17, 'The fetus is now about the size of a pear (5.1 inches). Sweat glands are developing and the skeleton is becoming bone.', 'Your center of gravity is changing, and your bump is more visible.', 'Practice good posture to minimize back pain.', 'Ensure adequate omega-3 fatty acids for brain development.', 'Increased appetite, stretch marks may begin, increased vaginal discharge.', 'Continue routine prenatal check-ups.', 'week17_pear.png'),

(18, 'The fetus is now about the size of a bell pepper (5.6 inches). The baby can yawn and hiccup.', 'You may have gained 8-10 pounds by now.', 'Start researching childbirth pain management options.', 'Include a variety of colorful fruits and vegetables in your diet.', 'Baby movements become more noticeable, backaches, leg cramps.', 'Anatomy scan ultrasound is typically scheduled between weeks 18-22.', 'week18_bell_pepper.png'),

(19, 'The fetus is now about the size of a tomato (6 inches). The senses of smell, taste, hearing, sight, and touch are developing.', 'Your uterus is about the size of a mango and is at the level of your belly button.', 'Explore options for childbirth classes in your area.', 'Stay adequately hydrated to help with amniotic fluid formation.', 'More defined baby movements, possible heartburn, and round ligament pain.', 'Anatomy scan ultrasound if not done already.', 'week19_tomato.png'),

(20, 'The fetus is now about the size of a banana (6.5 inches). Vernix caseosa (a waxy white coating) and lanugo (fine hair) cover the skin.', 'You''re halfway through your pregnancy! Your uterus is at the level of your belly button.', 'Begin counting baby''s kicks regularly to establish patterns.', 'Ensure adequate calcium intake for the developing skeleton.', 'Prominent baby movements, leg cramps, and mild swelling.', 'Comprehensive anatomy scan ultrasound if not done already.', 'week20_banana.png'),

(21, 'The fetus is now about the size of a carrot (10.5 inches). The baby can swallow and is practicing breathing movements.', 'You may need to adjust your sleeping position as your bump grows.', 'Start researching baby items you''ll need.', 'Include foods rich in vitamin A for eye development.', 'Braxton Hicks contractions may begin, backaches, and heartburn.', 'Review anatomy scan results with your provider.', 'week21_carrot.png'),

(22, 'The fetus is now about the size of a spaghetti squash (11 inches). The eyes have developed, though the irises still lack pigment.', 'Your skin may show more changes like the linea nigra (dark line down the middle of your abdomen).', 'Consider taking a hospital tour if that''s your planned birth location.', 'Focus on zinc-rich foods for immune system development.', 'Increased vaginal discharge, skin changes, and possible leg cramps.', 'Regular prenatal visit this month.', 'week22_spaghetti_squash.png'),

(23, 'The fetus is now about the size of a grapefruit (11.6 inches). The lungs are developing and preparing to breathe air.', 'Your uterus is about the size of a soccer ball.', 'Begin thinking about your birth plan preferences.', 'Include foods rich in choline for brain development.', 'Backaches, stretch marks may increase, and increased appetite.', 'Regular prenatal visit if scheduled.', 'week23_grapefruit.png'),

(24, 'The fetus is now about the size of a cantaloupe (12.2 inches). The baby has a regular sleep-wake cycle and may respond to sounds.', 'You may have gained about 15 pounds by now.', 'Begin preparing the baby''s living space.', 'Ensure adequate iodine intake for thyroid development.', 'Hemorrhoids, stretch marks, and Braxton Hicks contractions.', 'Glucose screening test for gestational diabetes.', 'week24_cantaloupe.png'),

(25, 'The fetus is now about the size of a rutabaga (13.2 inches). The baby is gaining more fat, and the lungs continue to develop.', 'Your uterus is about 2.5 inches above your belly button.', 'Finalize your childbirth education plans.', 'Focus on magnesium-rich foods for muscle development.', 'Increased baby activity, swelling in hands and feet, and lower back pain.', 'Regular prenatal visit this month.', 'week25_rutabaga.png'),

(26, 'The fetus is now about the size of a head of lettuce (14 inches). The eyes begin to open, and the baby may blink.', 'You may notice more prominent stretch marks as your skin stretches to accommodate the growing baby.', 'Begin thinking about pediatrician options.', 'Include foods rich in vitamin E for cell protection.', 'Braxton Hicks contractions may increase, trouble sleeping, and backaches.', 'Follow up on glucose screening results.', 'week26_lettuce.png');

-- Seed weeks 27-40 (Third Trimester)
INSERT INTO public.pregnancy_weeks (week, fetal_development, maternal_changes, tips, nutrition_advice, common_symptoms, medical_checkups, image_url) VALUES
(27, 'The fetus is now about the size of a cauliflower (14.4 inches). The brain is very active, and the baby can recognize voices.', 'You''re entering the third trimester! Your uterus is about 2.75 inches above your belly button.', 'Begin preparing for maternity leave if applicable.', 'Focus on foods rich in DHA for brain development.', 'Shortness of breath, increased urination, and heartburn.', 'Regular prenatal visit this month.', 'week27_cauliflower.png'),

(28, 'The fetus is now about the size of an eggplant (14.8 inches). The baby can open and close their eyes and may dream.', 'You may have gained 20-25 pounds by now.', 'Pack your hospital bag so it''s ready.', 'Stay hydrated to prevent constipation and swelling.', 'Back pain, leg cramps, and shortness of breath.', 'Rhogam shot given if you are Rh negative.', 'week28_eggplant.png'),

(29, 'The fetus is now about the size of a butternut squash (15.2 inches). The baby is gaining weight rapidly.', 'Your belly button may protrude. Your uterus extends about 3-4 inches above your belly button.', 'Make sure your car seat is properly installed.', 'Eat smaller, more frequent meals to help with heartburn.', 'Difficulty sleeping, frequent urination, and mild swelling.', 'Regular prenatal visit may be scheduled.', 'week29_butternut_squash.png'),

(30, 'The fetus is now about the size of a cabbage (15.7 inches). The baby''s brain is developing rapidly.', 'You may experience more Braxton Hicks contractions.', 'Finalize your birth plan if you haven''t already.', 'Include plenty of fiber to help combat constipation.', 'Backaches, heartburn, and trouble finding a comfortable sleeping position.', 'Prenatal visits may increase to every 2 weeks.', 'week30_cabbage.png'),

(31, 'The fetus is now about the size of a coconut (16.2 inches). The baby is practicing breathing and can turn their head from side to side.', 'Your uterus is getting crowded, so baby movements may feel different.', 'Practice relaxation techniques for labor.', 'Focus on vitamin K-rich foods for blood clotting ability.', 'Shortness of breath, heartburn, and fatigue.', 'Regular prenatal check-up.', 'week31_coconut.png'),

(32, 'The fetus is now about the size of a squash (16.7 inches). The baby''s bones are fully formed but still soft.', 'You may notice colostrum (pre-milk) leaking from your breasts.', 'Begin preparing freezer meals for after baby arrives.', 'Ensure adequate calories for the baby''s final growth spurt.', 'Braxton Hicks contractions, swelling, and difficulty sleeping.', 'Group B strep test may be performed.', 'week32_squash.png'),

(33, 'The fetus is now about the size of a pineapple (17.2 inches). The baby has fingernails, toenails, and real hair.', 'Your uterus extends about 5 inches above your belly button.', 'Finalize arrangements for help after the baby arrives.', 'Increase calcium intake for your baby''s growing skeleton.', 'Increased vaginal discharge, pelvic pressure, and back pain.', 'Regular prenatal visit.', 'week33_pineapple.png'),

(34, 'The fetus is now about the size of a cantaloupe (17.7 inches). The central nervous system and lungs are maturing.', 'You may have gained 25-30 pounds by now.', 'Learn the signs of preterm labor.', 'Include plenty of iron to prevent anemia before delivery.', 'Difficulty sleeping, swelling, and frequent urination.', 'Prenatal visits are now every two weeks.', 'week34_cantaloupe.png'),

(35, 'The fetus is now about the size of a honeydew melon (18.2 inches). The baby is gaining about half a pound a week.', 'You may feel the baby "dropping" as they move into position for birth.', 'Finalize your post-birth plans and supports.', 'Focus on easily digestible foods to help with stomach crowding.', 'Increased pelvic pressure, frequent urination, and possible lightning crotch pain.', 'Regular prenatal visit.', 'week35_honeydew.png'),

(36, 'The fetus is now about the size of a romaine lettuce head (18.7 inches). The baby is considered early-term.', 'Your uterus extends about 6 inches above your belly button.', 'Learn about signs of labor versus false labor.', 'Keep up healthy eating even though your appetite may decrease.', 'Pelvic pressure, difficulty sleeping, and increased fatigue.', 'Group B strep test if not done already.', 'week36_romaine_lettuce.png'),

(37, 'The fetus is now about the size of a head of Swiss chard (19.1 inches). The baby is considered full-term.', 'The baby may drop lower in your pelvis in preparation for birth.', 'Rest as much as possible and practice patience.', 'Focus on easily digestible foods for comfort.', 'Increased discharge, Braxton Hicks contractions, and pelvic pressure.', 'Weekly prenatal visits begin.', 'week37_swiss_chard.png'),

(38, 'The fetus is now about the size of a leek (19.6 inches). The baby''s organs are fully developed.', 'You may lose your mucus plug as your body prepares for labor.', 'Keep your phone charged and hospital route planned.', 'Stay hydrated to support amniotic fluid levels.', 'Insomnia, frequent urination, and possible cervical dilation.', 'Weekly prenatal visit with cervical check.', 'week38_leek.png'),

(39, 'The fetus is now about the size of a watermelon (20 inches). The baby is ready for birth.', 'You may experience more regular Braxton Hicks contractions.', 'Try natural induction methods if approved by your provider.', 'Focus on easily digestible, energy-providing foods.', 'Lightning crotch pain, increased pressure, and possible early labor signs.', 'Weekly prenatal visit with cervical check.', 'week39_watermelon.png'),

(40, 'The fetus is now about the size of a small pumpkin (20+ inches). The baby is fully developed and ready to meet you!', 'Your body is fully prepared for birth.', 'Know the signs of labor and when to go to the hospital.', 'Eat frequent small meals to maintain energy.', 'Possible birth signs: regular contractions, water breaking, or bloody show.', 'Weekly prenatal visit with possible induction discussion.', 'week40_pumpkin.png'); 