name: Deploy Bumb Buddy

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd bumpbuddy
          bun install

      # Skip linting for now
      # - name: Lint code
      #   run: |
      #     cd bumpbuddy
      #     bun run lint

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          # Try SSH key first, fallback to password if needed
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          timeout: 60s
          command_timeout: 15m
          debug: true
          # Allow both key and password authentication methods
          use_insecure_cipher: false
          script: |
            set -e  # Exit on any error
            echo "Starting deployment..."
            echo "Current user: $(whoami)"
            echo "Current directory: $(pwd)"
            echo "Server info: $(uname -a)"

            # Check if the directory exists
            if [ ! -d "/var/www/expo-app" ]; then
              echo "Error: /var/www/expo-app directory does not exist"
              echo "Available directories in /var/www:"
              ls -la /var/www/ || echo "Cannot access /var/www/"
              exit 1
            fi

            cd /var/www/expo-app
            echo "Pulling latest changes..."
            git pull origin main

            cd bumpbuddy
            echo "Installing dependencies..."
            bun install

            echo "Checking PM2 status..."
            pm2 list || echo "PM2 not found or not running"

            echo "Restarting PM2 service..."
            # Try different possible service names
            if pm2 list | grep -q "bumb-buddy"; then
              echo "Found bumb-buddy process, restarting..."
              pm2 restart bumb-buddy
            elif pm2 list | grep -q "bumpbuddy"; then
              echo "Found bumpbuddy process, restarting..."
              pm2 restart bumpbuddy
            elif pm2 list | grep -q "expo-app"; then
              echo "Found expo-app process, restarting..."
              pm2 restart expo-app
            else
              echo "Warning: No matching PM2 process found. Available processes:"
              pm2 list
              echo "Attempting to start new process..."
              pm2 start bun --name bumb-buddy -- start
            fi

            echo "Final PM2 status:"
            pm2 list
            echo "Deployment completed successfully!"
